server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: Shreya@2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 31527928201-d9h78t8n7fe7435ldd294bk7druth8mb.apps.googleusercontent.com
            client-secret: 31527928201-d9h78t8n7fe7435ldd294bk7druth8mb.apps.googleusercontent.com
            scope: profile, email
          github:
            client-id: your-github-client-id
            client-secret: your-github-client-secret
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/user
            user-name-attribute: sub

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: mysecretkeymysecretkeymysecretkey12345